<?php

namespace vdm_campingBundle\Repository;

/**
 * vdm_tableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class vdm_tableRepository extends \Doctrine\ORM\EntityRepository
{
}
